cmd/root.go, internal/pkg/changelog/changelog.go, internal/pkg/githubclient/githubclient.go
This PR adds the foundational code for better error handling. It largely draws from the code in gh-cli that allows for better error customization.
It fixes issues #1 and #2.
=> Implement better errors

internal/pkg/markdown/markdown.go, internal/pkg/writer/writer.go
This PR sets the line length for markdown rendering to 140 characters. It's a little bit more than the recommended of 80-100 characters, but it seems to fit the terminal well.
=> Set longer line length for md render

internal/pkg/gitclient/gitclient.go, internal/pkg/writer/writer.go
Prior to this commit, the last tag could potentially be compared with a commit that was not part of the current tree. This caused an invalid comparison.
This PR fixes that by using a git log equivalent to get the correct commit history.
=> Fixes root commit reference

README.md, cmd/new.go, cmd/show.go, internal/pkg/changelog/changelog.go, internal/pkg/changelog/properties.go, internal/pkg/configuration/configuration.go, internal/pkg/writer/writer.go
Prior to this PR, it was not clear how to configure this tool. There were defaults set within the application but you needed to look at the source code to find out what they were.
This PR improves the config system by writing out a config file that contains the defaults supported by the application.
Closes #26
=> Better config

.github/workflows/ci.yml, Makefile, README.md, cmd/new.go, go.mod, go.sum, internal/pkg/changelog/changelog.go, internal/pkg/configuration/configuration.go, internal/pkg/gitclient/client.go, internal/pkg/githubclient/client.go, internal/pkg/githubclient/client_test.go, internal/pkg/utils/utils.go, internal/pkg/utils/utils_test.go, internal/pkg/writer/writer.go, internal/pkg/writer/writer_test.go, mocks/Changelog.go, mocks/ChangelogBuilder.go, mocks/GitClient.go
This PR adds support for an unreleased section and also adds an optional next-version flag.
The unreleased section will display any qualifying entries that have been added since the last tag.
The next-version flag allows the user to specify an arbitrary version number to use for the next release. 
If used, any qualifying entries that have been added since the last tag will be grouped here and the unreleased section will not be shown.
=> Implementation of next-version and unreleased

cmd/root.go, internal/pkg/markdown/markdown.go
Prior to this commit, when the application exited with an error, the resulting message did not contain a red cross.
This commit adds the red cross to the error message. However it is only done in the root execute function.
=> Fix error messages

cmd/new.go, cmd/root.go, cmd/show.go, internal/pkg/changelog/builder.go, internal/pkg/configuration/configuration.go
This PR reworks how configuration is consumed throughout the app.
Previously, we would call viper directly in respective packages to retrieve configuration values. Now, we unmarshal; in to a struct and consume it where required.
=> Rework configuration

internal/pkg/configuration/configuration_test.go
This PR adds a basic test to ensure that the configuration struct is being initialized correctly.
=> Add a test for configuration setup

internal/pkg/writer/writer.go
Keep a changelog does not have perentheses around the date for each
version.
This commit removes the perentheses.
=> Ensure that Keep a Changelog format is followed

internal/pkg/changelog/builder.go, internal/pkg/changelog/builder_test.go, internal/pkg/changelog/changelog.go, internal/pkg/changelog/changelog_test.go, internal/pkg/githubclient/client_test.go, internal/pkg/writer/writer_test.go
This commit adds gets for the `changelog` package.
It also includes some refactoring of `builde`r & `changelog` to use some modified methods that were changed while writing tests.
Writer tests have also been updated to use the new `NewChangelog` method.
=> Tests for changelog package

README.md, internal/pkg/configuration/configuration.go
Prior to this PR users could only configure the application via the config file.
This PR enables vipers automatic environment feature to allow optional configuration from environment variables.
Closes #55
=> Enable configuration from environment

README.md, cmd/config.go, cmd/root.go, go.mod, go.sum, internal/pkg/configuration/configuration.go, internal/pkg/configuration/configuration_test.go
Prior to this PR it was only possible to view config by inspecting the config file created in the users home directory or the current environment variables if any settings had been overridden.
This PR adds the `config` command that allows users to print the current configuration of the application to stdout in either yaml or json format.
Closes #39
=> Add a command to view current config

internal/pkg/changelog/builder.go, internal/pkg/gitclient/client.go, internal/pkg/gitclient/client_test.go
This PR adds tests for the `gitclient`. The test implementation used meant that `gitclient` needed to be slightly refactored so that we can pass in a fake command context when required.
=> Add gitclient tests

cmd/config.go, internal/pkg/configuration/configuration.go
After reading an article about unit testing stdout, it became clear that using `bufio` for this specific case was overkill. os.Stdout actually implements the writer interface, therefore it's possible to pass it straight in to the methods and switch out `writer.Write` for `fmt.Fprint`.
=> Simplify config printing

internal/pkg/gitclient/client.go, internal/pkg/gitclient/client_test.go
Sometimes repositories can contain more than one commit with no parents.
This meant that in some situations GetFirstCommit() could return more than one SHA, causing the application to break as downstream methods would not expect the input.
This PR handles this edge case by reversing the order of commits from rev-list, splitting by new line and always returning the sha at position 0.
In theory this should always be the oldest commit in the repository.
In the future logging should be added here.
Fixes #73
=> Handle orphaned commits

internal/pkg/changelog/builder.go, internal/pkg/changelog/builder_test.go, internal/pkg/utils/utils.go, internal/pkg/utils/utils_test.go
This PR adds validation to ensure that the value being passed to next version is greater than the former version. If the condition is not true an error will be returned.
Closes #76
=> Validate next version

cmd/config.go, go.mod, internal/pkg/configuration/configuration.go, internal/pkg/configuration/configuration_test.go
This PR adds optional colorization of the config output. In certain situations this can make reading configuration easier and it also looks pretty neat.
There is also an optional --no-color flag that can be passed. This will disable set the chroma formatter to `noop` rather than terminal16m. Currently, the data is still tokenized by chroma but not formatted so it does not print with any ascii codes.
In this implementation it doesn't matter too much because the size of the configuration will always been small so there are no major tradeoffs.. an improved solution could be to skip passing through chroma if the --no-color flag is passed!
=> Colorize config output

internal/pkg/configuration/configuration.go
The lexer was set incorrectly to json in the PrintYaml method. This lead to broken colourisation of the config when printing as yaml.
In this PR we update the lexer to `yaml`.
=> Fix lexer in PrintYAML method

internal/pkg/configuration/configuration.go
This PR adds the `dependencies` label as a default value for the excluded_labels configuration property.
This is so that PRs from dependabot do not show up in changelogs.
=> Add a new excluded label default

internal/changelog/builder.go, internal/changelog/builder_test.go
Prior to this commit when `gh changelog new` was executed on a repository with no tags it would cause an `index out of range` error. This error was not handled and would be displayed to the user.
This commit fixes that by checking the length of the tags slice that is returned from `GetTags`. If it is 0 then we return an error so that it properly bubbles up to the user.
=> Properly handle a repo with no tags

.github/workflows/codeql-analysis.yml
This commit disables codeql triggers for pushes to main and pullrequests.
=> Disable codeql triggers

cmd/new.go, go.mod, go.sum, internal/configuration/configuration.go, internal/configuration/configuration_test.go, internal/environment/environment.go, internal/environment/environment_test.go, internal/logging/logger.go, internal/logging/logger_test.go, internal/logging/spinner.go, internal/logging/text.go, pkg/builder/builder.go, pkg/builder/builder_test.go
This commit adds a new internal package called logging. It exposes the Logger interface. The package also includes two loggers that implement the Logger interface.
TEXT - this logger uses zerolog and will print out a sequential list of events.
SPINNER - even though this is technically not a logger, this option implements a spinner that is used to display events.
The type of logger used is determined by the LoggerType options. The LoggerType is passed to the constructor which will return the correct logging implementation.
=> Better logging control

pkg/builder/builder.go
This commit fixes an issue where nextVersion would get inserted at the end of the array when infact it should have been inserted at the start.
=> Fix tags append

internal/writer/writer.go, pkg/builder/builder.go, pkg/builder/builder_test.go
Prior to this PR the markdown created by this extension would cause markdownlint violations.
This commit ensure that these are fixed.
For MD024 (duplicate headings) a disable comment has now been added to the top of the file.
=> Fix markown formatting

pkg/builder/builder.go, pkg/builder/builder_test.go
Prior to this change, if the tool was ran on a repo with no tags (a new project for example) it would fail because there were no tags returned by githubs api.
This change fixes that by updating the builder so that an error is generated only if there are no tags and the --next-version flag has not been provided.
=> Fix usage on repositories without tags

.changelog.yml, internal/configuration/configuration.go
This commit adds the current working directory as a search path for viper.
It also changes the name of the configuration file to `.changelog.yml`.
If there is a `.changelog.yml` file present in the current directory, gh-changelog will prefer this over the one that is created inside `.config/gh-changelog`.
=> Allow local configs

internal/utils/utils.go, internal/utils/utils_test.go
Prior to this change, the generator could not handle pre-releases.
This change updates `utils.VersionIsGreaterThan` so that it uses compare vs the previous constraint.
`Comparse` will take in to consideration pre-releases where as constraints did not.
https://pkg.go.dev/github.com/Masterminds/semver/v3#Version.Compare
=> Handle Pre-Releases

internal/utils/utils.go, internal/utils/utils_test.go, internal/version/version.go, pkg/builder/builder.go
In this change we are temporarily patching the code that handles version parsing.
The code in package version has been borrowed from SemVer/v3/version and slightly adapted to help this tool work arround an issue caused by different pre-release delimeters.
The package can be removed when/if SemVer supports this.
=> Patch Version Parsing Code

internal/writer/writer.go
In order to better match changes that follow semver, group changes that
trigger a MAJOR bump ("Changed", "Removed") _before_ those that trigger
a MINOR bump ("Added"), _before_ those that trigger a PATCH bump
("Fixed").
"Security", "Deprecated" and "Other" changes do not have a corresponding
part as far as semver is concerned, so put them where it makes more
sense: "Security" at the top, "Deprecated" just after "Removed" and
"Other" at the end.
The ordering is now:
- Security
- Changed
- Removed
- Deprecated
- Added
- Fixed
- Other
=> Improve sections ordering

internal/writer/writer.go
When a release has breaking changes, they are listed in a "Changed"
section.  Unlike other sections, this section title is directly followed
by the change list, while other sections have a blank line to separate
the title and the change list.
For consistency make sure we have that blank line after all titles.
=> Add missing line between "Changed" title and list

internal/get/get.go, internal/get/get_test.go, internal/writer/writer.go, internal/writer/writer_test.go, pkg/entry/entry.go
=> Fix no previous tag when using get cmd

internal/get/get.go, internal/get/get_test.go, internal/get/single_CHANGELOG.md
* Caused by #148
* Reproduce with a single entry CHANGELOG.md (added test)
```
$ gh-changelog get --latest
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xafc65d]
goroutine 1 [running]:
github.com/chelnak/gh-changelog/internal/get.changelogWithSingleEntry({0x0, 0x0, {0xc000512428, 0x6}, {0x0, 0x0}, {0x0, 0xeddc4ce80, 0x0}, {0x0, ...}, ...}, ...)
/home/h0tw1r3/dev/gh-changelog/internal/get/get.go:31 +0x5d
github.com/chelnak/gh-changelog/internal/get.GetLatest({0xc000473340?, 0x0?})
/home/h0tw1r3/dev/gh-changelog/internal/get/get.go:70 +0x10e
github.com/chelnak/gh-changelog/cmd.glob..func2(0x2354fc0?, {0xe2e32c?, 0x1?, 0x1?})
/home/h0tw1r3/dev/gh-changelog/cmd/get.go:43 +0x67 …
```
=> Fix get latest panic on single entry changelog

cmd/get.go, cmd/new.go, internal/writer/writer.go, internal/writer/writer_test.go
Basically an alternate template to the changelog format that only works with a single "Entry" and doesn't output the changelog header or footer.
A "full" changelog style entry is usually not desired when adding to annotated tags or a Github release message.
Ideally, as this extension is GH specific, I would like to see the release notes more release friendly (automatic contributors section).
Instead of this:
```markdown
- Improve sections ordering https://github.com/chelnak/gh-changelog/pull/139 ([smortex](https://github.com/smortex))
```
Output this for release notes:
```markdown
- #139: Improve sections ordering (@smortex)
```
Which ends up looking like:
=> add new notes output to get command
